### ISSUE TITLE
Issue about building

### ISSUE THREAD

**Issue by justmert** [marko-knoebl/rehype-slides-starter#1]
While i follow instructions,
I have encountered this problem:

![image](https://user-images.githubusercontent.com/37740842/97725467-40ac6080-1adf-11eb-8b36-7f9d865c55c4.png)

Could you help me to fix this ?

**Comment by justmert** [comment]
Okey, i have resolved it.
I have run these commands respectively,
```
npm install
npm run build
node scripts/build.js
```
Then. my html files have been created in _dist_ directory. Thanks

**Comment by marko-knoebl** [comment]
Thanks for reporting this. I've just updated the readme (I've included `npm install` which was missing before)
